### ISSUE TITLE
Doesn't work on Gnome Shell 3.32

### ISSUE THREAD

**Issue by AndreaOrru** [JasonLG1979/gnome-shell-extensions-mpris-indicator-button#2]
## Distro Name & Version
Arch Linux

## GNOME Shell Version
3.32

## Other Installed Extensions

No other third party extensions.

## Expected Behavior

An icon appears on the top right corner of the screen.

## Current Behavior

The icon does not appear.

## Detailed Description

Notifications work, but icon doesn't appear.

**Comment by JasonLG1979** [comment]
@AndreaOrru When Fedora get past it's beta, here hopefully in a couple weeks, I'll start testing against  GNOME 3.32. Not that Fedora is the be all, end all of distro's, it just happens to be what I personally use so I generally support whatever GNOME version is used by the current Fedora release since it's my daily driver.

**Comment by AndreaOrru** [comment]
:+1: It can wait :)

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-mpris-indicator-button/commit/de5fbdc35a0935aa83a9688e8bbb249de2c1e267 Should make the extension work in GNOME Shell 3.32 thanks to @pcm720.

**Comment by JasonLG1979** [comment]
I will package and push to https://extensions.gnome.org here in a bit but it can take a while to get approved there. I'm still waiting on a review from an update I pushed in late January.

**Comment by JasonLG1979** [comment]
A version for 3.32 has been pushed to https://extensions.gnome.org it is currently awaiting review and approval.
